apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "kuadrant.io/v1alpha1",
          "kind": "DNSHealthCheckProbe",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "kuadrant-dns-operator",
              "app.kubernetes.io/instance": "dnshealthcheckprobe-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "dnshealthcheckprobe",
              "app.kubernetes.io/part-of": "kuadrant-dns-operator"
            },
            "name": "dnshealthcheckprobe-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "kuadrant.io/v1alpha1",
          "kind": "DNSRecord",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "kuadrant-dns-operator",
              "app.kubernetes.io/instance": "dnsrecord-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "dnsrecord",
              "app.kubernetes.io/part-of": "kuadrant-dns-operator"
            },
            "name": "dnsrecord-sample"
          },
          "spec": {
            "endpoints": [
              {
                "dnsName": "dnsrecord-simple.example.com",
                "recordTTL": 60,
                "recordType": "A",
                "targets": [
                  "52.215.108.61",
                  "52.30.101.221"
                ]
              }
            ],
            "managedZone": {
              "name": "managedzone-sample"
            }
          }
        },
        {
          "apiVersion": "kuadrant.io/v1alpha1",
          "kind": "ManagedZone",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "kuadrant-dns-operator",
              "app.kubernetes.io/instance": "managedzone-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "managedzone",
              "app.kubernetes.io/part-of": "kuadrant-dns-operator"
            },
            "name": "managedzone-sample"
          },
          "spec": {
            "description": "My managed domain",
            "domainName": "example.com"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-02-02T21:32:57Z"
    operators.operatorframework.io/builder: operator-sdk-v1.33.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: kuadrant-dns-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DNSHealthCheckProbe is the Schema for the dnshealthcheckprobes
        API
      displayName: DNSHealth Check Probe
      kind: DNSHealthCheckProbe
      name: dnshealthcheckprobes.kuadrant.io
      version: v1alpha1
    - description: DNSRecord is the Schema for the dnsrecords API
      displayName: DNSRecord
      kind: DNSRecord
      name: dnsrecords.kuadrant.io
      version: v1alpha1
    - description: ManagedZone is the Schema for the managedzones API
      displayName: Managed Zone
      kind: ManagedZone
      name: managedzones.kuadrant.io
      version: v1alpha1
  description: Kuadrant DNS Operator
  displayName: Kuadrant DNS Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - kuadrant.io
          resources:
          - dnshealthcheckprobes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kuadrant.io
          resources:
          - dnshealthcheckprobes/finalizers
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - dnshealthcheckprobes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - dnsrecords
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kuadrant.io
          resources:
          - dnsrecords/finalizers
          verbs:
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - dnsrecords/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - managedzones
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - kuadrant.io
          resources:
          - managedzones/finalizers
          verbs:
          - update
        - apiGroups:
          - kuadrant.io
          resources:
          - managedzones/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: kuadrant-dns-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: kuadrant-dns-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: kuadrant-dns-operator
          control-plane: controller-manager
        name: kuadrant-dns-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: kuadrant-dns-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: kuadrant-dns-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - dns
  links:
  - name: Kuadrant DNS Operator
    url: https://kuadrant-dns-operator.domain
  maintainers:
  - email: mnairn@redhat.com
    name: Michael Nairn
  - email: pbrookes@redhat.com
    name: Phil Brookes
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
