resources:
  - ../base

nameSuffix: -gcp

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: managed-zone-config
    envs:
      - managed-zone-config.env
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

secretGenerator:
  - name: dns-provider-credentials
    envs:
      - gcp-credentials.env
    type: "kuadrant.io/gcp"

replacements:
  - source:
      kind: ConfigMap
      name: managed-zone-config
      version: v1
      fieldPath: data.GCP_ZONE_NAME
    targets:
      - select:
          kind: ManagedZone
          name: dev-mz-gcp
        fieldPaths:
          - spec.id
  - source:
      kind: ConfigMap
      name: managed-zone-config
      version: v1
      fieldPath: data.GCP_ZONE_DNS_NAME
    targets:
      - select:
          kind: ManagedZone
          name: dev-mz-gcp
        fieldPaths:
          - spec.domainName
