apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  labels:
    app.kubernetes.io/name: dnsrecord
    app.kubernetes.io/instance: dnsrecord-sample
    app.kubernetes.io/part-of: kuadrant-dns-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kuadrant-dns-operator
  name: dnsrecord-sample
spec:
  # TODO(user): Add fields here
