# Local deployment overlay.
#
# Set the deployment imagePullPolicy to IfNotPresent. This is required if you are using a local image loaded into kind i.e. make kind-load-image
#

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../default

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --provider=aws,google,inmemory,azure
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --zap-log-level=debug
    target:
      kind: Deployment
  - path: manager_config_patch.yaml
