resources:
  - ../base

nameSuffix: -aws

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: managed-zone-config
    envs:
      - managed-zone-config.env
    options:
      annotations:
        config.kubernetes.io/local-config: "true"

secretGenerator:
  - name: dns-provider-credentials
    envs:
      - aws-credentials.env
    type: "kuadrant.io/aws"

replacements:
  - source:
      kind: ConfigMap
      name: managed-zone-config
      version: v1
      fieldPath: data.AWS_DNS_PUBLIC_ZONE_ID
    targets:
      - select:
          kind: ManagedZone
          name: dev-mz-aws
        fieldPaths:
          - spec.id
  - source:
      kind: ConfigMap
      name: managed-zone-config
      version: v1
      fieldPath: data.AWS_ZONE_ROOT_DOMAIN
    targets:
      - select:
          kind: ManagedZone
          name: dev-mz-aws
        fieldPaths:
          - spec.domainName
